FORMAT: 1A
HOST:http://140.116.247.120:5000

# Energy Trading (ET) API Document

ET's back-end API<p>
API-version: 0.1

# Group Restful

## Login [/login]

Used to login platform.

### Login [POST]
<pre>
curl http://140.116.247.120:5000/login -X POST -H "Content-Type: application/json" -d '{"account": "TestA1", "password": "TestA1"}'
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1

    + Attributes
        + account: `TestA1` - Login Account
        + password: `TestA1` - Account's Password

+ Response 200 (application/json)
    + Attributes
        + id: `03f87a5a-a4e6-4536-ba6c-265c03ebd317` - User's UUID
        + bearer: `OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR` - Authentication Bearer Token

+ Response 401 (application/json)
    + Attributes
        + error: `Unauthorized access` - Authentication failed

## User [/user]

User's information.

### User Info [GET]
<pre>
curl http://140.116.247.120:5000/user -X GET -H "Content-Type: application/json" -H "Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR"
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

+ Response 200 (application/json)
    + Attributes
        + username: `TestA1`
        + avatar: `https://imgur.com/0JMAdHM` - Profile Picture's URL
        + balance: `100` (number) - User's Token balance
        + address: `台南市大學路一號` - User's Building Address
        + eth_address: `0xB346ef4EEFc02FdAa7b4756Db4F30E0cdA9704Ae` - User's ETH Address
        + is_aggregator: `true` - User's aggregator authority

### Change Password [PUT]
<pre>
curl http://140.116.247.120:5000/user -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR" -d '{"original_passwd": "TestA1","new_passwd": "new_password"}'
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

    + Attributes
        + original_passwd: `User1pwd` - User input original password
        + new_passwd: `User1new` - User input new password

+ Response 200 (application/json)
    + Attributes
        + message: Accept.


+ Response 400 (application/json)
    + Attributes
        + message: Fail. - Error Message

### Create User [POST]
<pre>
curl http://140.116.247.120:5000/user -X POST -H "Content-Type: application/json"
  -d '{
        "account": "TestA1",
        "username": "TestA1_BEMS",
        "password": "test"
}'
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1

    + Attributes
        + account: `TestA1` - Account name, ID
        + username: `TestA1` - Account username
        + password: `test` - Account password

+ Response 200 (application/json)
    + Attributes
        + message: Account created


+ Response 400 (application/json)
    + Attributes
        + message: `{error-message}` - Error Message

## AMI [/amis]

Get User's AMIs.

### AMIs [GET]
<pre>
curl http://140.116.247.120:5000/amis -X GET -H "Content-Type: application/json" -H "Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR"
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

+ Response 200 (application/json)
    + Attributes (array, fixed-type)
        + (object)
            + id: `a6d2a4cd-fc78-4636-9c42-c0006976244b` - UUID
            + name: `智駕車BEMS`
            + description: `智駕車總表AMI` - AMI 名稱

## News [/news]

Get latest ten system news.

### News [GET]
<pre>
curl http://140.116.247.120:5000/news -X GET -H "Content-Type: application/json" -H "Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR"
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

+ Response 200 (application/json)
    + Attributes (array, fixed-type)
        + (object)
            + id: `5f3276c2-ec53-4dd3-ada3-081ca3f9d4f9` - The news' UUID
            + time: `2019/08/25 10:00` - The Message Upload Date
            + content: `Website Upload to Version 0.2` - The Message Content

## Bid Submit [/bidsubmit]

Related to bidding.

### Bidding Project [GET /bidsubmit{?per_page}{?page}{?bid_type}]
<pre>
curl http://140.116.247.120:5000/bidsubmit?per_page=10&page=5&bid_type=buy -X GET -H "Content-Type: application/json" -H "Authorization: Bearer 3MaTIcta709SxWZ88OkaLjKvNzgfFkxqr8WemUjeOKLZcImscV6WcziuFyfrbXjc"
</pre>

Return the bid content valid from the day (Today, current time).

+ Parameters
    + per_page: `10` (number) - 一頁的標案數量.
    + page: `5` (number) - 頁面數.
    + bid_type: `buy` (string) - 取得買或賣的標案資料

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

+ Response 200 (application/json)
    + Attributes
        + data (array) - 頁面所顯示的標案資訊
            + (BidSubmit1) - 第一筆資料
            + (BidSubmit2) - 第二筆資料
        + page: `1` (number) - 所在頁數
        + totalCount: `20` (number) - 在當時間總共有效的標案

### Order [POST]
<pre>
curl http://140.116.247.120:5000/bidsubmit -X POST -H 'Authorization: Bearer 3MaTIcta709SxWZ88OkaLjKvNzgfFkxqr8WemUjeOKLZcImscV6WcziuFyfrbXjc' -H 'Content-Type: application/json' \
  -d '{
    "bid_type": "buy",
    "start_time": "2019/10/29 18",
    "end_time": "2019/10/29 19",
    "value": 10,
    "price": 6.8
}'
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

    + Attributes
        + bid_type: `buy` - Bidding type: sell or buy
        + start_time: `2019/09/01 13` - Bidding Datetime Start
        + end_time: `2019/09/01 14` - Bidding Datetime End
        + value: `10` (number) - kWh
        + price: `4.3` (number) - NT Dollars

+ Response 200 (application/json)
    + Attributes
        + message: Accept

+ Response 400 (application/json)
    + Attributes
        + message: Reject

### Edit [PUT]
<pre>
curl http://140.116.247.120:5000/bidsubmit -X PUT -H 'Authorization: Bearer 3MaTIcta709SxWZ88OkaLjKvNzgfFkxqr8WemUjeOKLZcImscV6WcziuFyfrbXjc' -H 'Content-Type: application/json' \
  -d '{
    "id": "2048b3c9-0125-41fc-bef6-9b1e52bd825f",
    "bid_type": buy,
    "start_time": "2019/10/29 18",
    "end_time": "2019/10/29 19",
    "value": 10,
    "price": 6.8
}'
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

    + Attributes
        + id: `104fa450-c688-4f7f-8cca-fae7a18f2eb8` - Item's UUID
        + bid_type: `buy` - Bidding type: sell or buy
        + start_time: `2019/09/01 13` - Bidding Datetime Start
        + end_time: `2019/09/01 14` - Bidding Datetime End
        + value: `10` (number) - kWh
        + price: `4.3` (number) - NT Dollars

+ Response 200 (application/json)
    + Attributes
        + message: Accept

+ Response 400 (application/json)
    + Attributes
        + message: Reject

### Remove [DELETE]
<pre>
curl http://140.116.247.120:5000/bidsubmit -X DELETE -H 'Authorization: Bearer 3MaTIcta709SxWZ88OkaLjKvNzgfFkxqr8WemUjeOKLZcImscV6WcziuFyfrbXjc' -H 'Content-Type: application/json' -d '{"id": "104fa450-c688-4f7f-8cca-fae7a18f2eb8"}'
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

    + Attributes
        + id: `104fa450-c688-4f7f-8cca-fae7a18f2eb8` - Remove item's UUID

+ Response 200 (application/json)
    + Attributes
        + message: Accept

+ Response 400 (application/json)
    + Attributes
        + message: Reject
        + description: The bid has been closed - Error message


## Home Page [/homepage]

Return information for home page.

### Home Page [GET]
<pre>
curl http://140.116.247.120:5000/homepage -X GET -H "Content-Type: application/json" -H "Authorization: Bearer 3MaTIcta709SxWZ88OkaLjKvNzgfFkxqr8WemUjeOKLZcImscV6WcziuFyfrbXjc"
</pre>

Return detail information sets for home page which includes current execution info and 10 most recent succuessful bid results (if any).

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

+ Response 200 (application/json)
    + Attributes
        + executing - 首頁即時交易資訊 (當時段)。如果沒有執行階段，則以下皆 null。
            + bid_type: `buy` - 買賣類別
            + price: 4.0 (number) - 交易價錢
            + volume: 40 (number) - 交易電量
        + results (array) - 最近十筆得標成功的資料 (if any)
            + (HomepageBid1) - 第一筆資料
            + (HomepageBid2) - 第二筆資料

## Match Result [/matchresult]

Return match results.

### Match Result [GET]
<pre>
curl http://140.116.247.120:5000/matchresult -X GET -H "Content-Type: application/json" -H "Authorization: Bearer 3MaTIcta709SxWZ88OkaLjKvNzgfFkxqr8WemUjeOKLZcImscV6WcziuFyfrbXjc"
</pre>

Return details information sets of the user's bids.

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

+ Response 200 (application/json)
    + Attributes (array, fixed-type)
        + (BID)


## Schematic Diagram [/participant]

Return participants in the transaction to paint schematic diagram.

### Participants [GET]
<pre>
curl http://140.116.247.120:5000/participant -X GET -H "Content-Type: application/json" -H "Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR"
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

+ Response 200 (application/json)
    + Attributes (array, fixed-type)
        + (object)
            + id: `7e54877b-3743-4d20-bbfc-5b4deb131116` - User's UUID
            + name: `BEMS1`

## Power Info [/power_info]

Return Electricity History Usage.

### PowerData (Data Table Mode) [GET /power_info{?per_page}{?page}{?time}]
<pre>
curl http://140.116.247.120:5000/power_info?per_page=10&page=1&time=2020/02/14 -X GET -H "Content-Type: application/json" -H "Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR"
</pre>

+ Parameters
    + per_page: `10` (number, required) - Power data per page.
    + page: `1` (number, required) - Power data at page.
    + time: `2020/02/14` (string, optional) - Date for the data, default is now, format YYYY/MM/DD.

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

+ Response 200 (application/json)
    + Attributes
        + data (array) - 頁面所顯示的電力資訊
            + (PowerEntry1) - 第一筆資料
            + (PowerEntry2) - 第二筆資料
        + page: `1` (number) - 所在頁數
        + totalCount: `785` (number) - Query 時間內資料總數

### PowerData (Data Chart Mode) [GET /power_info{?start_time}{?end_time}]
<pre>
curl http://140.116.247.120:5000/power_info?start_time=2020/02/14?end_time=2020/02/15 -X GET -H "Content-Type: application/json" -H "Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR"
</pre>

+ Parameters
    + start_time: `2020/02/14` (string, required) - Date for the data, format YYYY/MM/DD.
    + end_time: `2020/02/15` (string, required) - Date for the data, format YYYY/MM/DD.

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

+ Response 200 (application/json)
    + Attributes (array, fixed-type)
        + (ChartData1) - 產用電資訊 1
        + (ChartData2) - 產用電資訊 2

# Group Web Socket
## Association Diagram [/s1]

Return transaction status.

### Association [OPTIONS /socket/association]
<pre>
NOT YET !!!!!!
</pre>

+ Request (application/json)
    + Headers

            API-version: 0.1
            Authorization: Bearer OXBiogjCfdKb7m9CEOPhpbjjv0n5OtfltzgMJbSxbP7jVFY8XUNzHqkGidDumQSR - Authentication Bearer Token

    + Attributes
        + event: association - Socket Event Name

+ Response 200 (application/json)
    + Attributes (array, fixed-type)
        + (object)
            + seller: `e900b7b0-c097-4ce8-9426-7399d6412b26` - Seller's UUID
            + buyer: `9eef88ba-abf3-4cdc-a2cc-c63e331c4c47` - Buyer's UUID
            + value: `10` (number) - win value
            + achievement: `4` (number)

## Data Structures
### BID (object)
+ id: `b345273d-ffc9-4916-bf7e-5615f0ee8a39` - Message's UUID
+ date: `2019/09/01` - Trade Target Date
+ time: `13:00-14:00` - Trade Period
+ bid_type: `sell` - sell or buy
+ bids
    + price: `5.0` (number) - Bidding Price
    + value: `20.0` (number) - Bidding Value
+ status: `已結算` - Bidding Status
+ transaction_hash: `0xdb13d6c572a482f2a9578bfb3cc41a2f0e349852138e788db795ee51ce40b439` - Transaction Hash
+ counterpart
    + name: 沙崙綠能科學城C區BEMS
    + address: 台南市歸仁區高發二路360號C區
+ win: `1` (number) - Deal or No Deal
+ wins
    + value: `10` (number) - Winning Value
    + price: `50` (number) - Winning Total Price
+ upload: `Thu, 12 Mar 2020 14:15:00 GMT` - Upload Time
+ achievement: `100%` - 0~100%
+ settlement: `50` (number) - Settlement Transaction Price

### BidSubmit1
+ bid_type: `buy` (string) - 投標類型
+ date: `2020/10/29` (string) - 目標執行日期 YYYY/MM/DD
+ end_time: `2020/10/29 19` (string) - 執行結束時間
+ id: `049a9c28-c0cc-418e-9f35-23f6bc43df7e` - 投標 UUID
+ price: `6.8` (number) - 投標單價
+ start_time: `2020/10/29 18` (string) - 執行開始時間
+ time: `18` (number) - 執行時間
+ total_price: `68.0` (number) - 總交易價格
+ upload_time: `Sat, 21 Mar 2020 14:28:59 GMT` (string) - 投標上傳時間
+ volume: `10` (number) - 投標電量

### BidSubmit2
+ bid_type: `buy` (string) - 投標類型
+ date: `2020/10/230` (string) - 目標執行日期 YYYY/MM/DD
+ end_time: `2020/10/30 7` (string) - 執行結束時間
+ id: `b6953af5-0803-4559-af5c-115613627624` - 投標 UUID
+ price: `4.771` (number) - 投標單價
+ start_time: `2020/10/30 6` (string) - 執行開始時間
+ time: `6` (number) - 執行時間
+ total_price: `47.71` (number) - 總交易價格
+ upload_time: `Sat, 21 Mar 2020 14:28:59 GMT` (string) - 投標上傳時間
+ volume: `10` (number) - 投標電量

### HOMEPAGE
+ table: `homepage`
+ id: `b6953af5-0803-4559-af5c-115613627624` - Data's UUID
+ field: `NCKU` (string) - 場域
+ grid: `2.516` (number) - 電網即時功率
+ pv: `0.000` (number) - 太陽能即時功率
+ building: `2.466` (number) - 大樓即時用電
+ ess: `0.000` (number) - 儲能即時功率
+ ev: `0.000` (number) - 充電樁即時功率
+ updated_at: `2019-09-04T12:00:00` - 資料上傳時間

### ESS
+ table: `ess`
+ id: `486fbca4-9bc1-42bd-af93-92ceb77d89ec` - Data's UUID
+ field: `NCKU` (string) - 場域
+ cluster: `1` (number) - ESS編號
+ power_display: `-0.035` (number) - 讀取實功輸出(kW)
+ updated_at: `2019-09-04T12:00:00` - 資料上傳時間

### EV
+ table: `ev`
+ id: `c363a32e-3dbe-42c5-bfe2-398436192c6f` - Data's UUID
+ field: `NCKU` (string) - 場域
+ cluster: `1` (number) - 充電柱編號
+ power_display: `0.000` (number) - 充電功率(kW)
+ updated_at: `2019-09-04T12:00:00` - 資料上傳時間

### PV
+ table: `pv`
+ id: `e257ccca-409a-4297-a6c2-c6d91b6dd334` - Data's UUID
+ field: NCKU (string) - 場域
+ cluster: `1` (number) - 太陽能編號
+ PAC: 0.000 (number) - 市電功率
+ updated_at: `2019-09-04T12:00:00` - 資料上傳時間

### WT
+ table: `wt`
+ id: `c15107ab-afed-4d9c-a123-ca6d0626d868` - Data's UUID
+ field: `NCKU` (string) - 場域
+ cluster: `1` (number) - 風機編號
+ WindGridPower: `0.000` (number) - 風機功率
+ updated_at: `2019-09-04T12:00:00` - 資料上傳時間

### PowerEntry1
+ address: `https://thetangle.org/transaction/WGQEE9ZNHHNPZ9AILVK9NAUXTRQZWJVEMIXWPBMWFQZTRXLIURDKLVUKACJAQIJOCKDWAZTLTLZY99999` - IOTA address
+ data_type: `ESS` - 產能設備
+ date: `2020/02/14` - 日期
+ id: `049a9c28-c0cc-418e-9f35-23f6bc43df7e` - PowerData UUID
+ power_display: `4.771` (number) - 電力資訊
+ time: `23:50` - 時間

### PowerEntry2
+ address: `https://thetangle.org/transaction/QAYPUZOKFXCDXGL9ZUZNVMKRNYGPSYRDQNJDQBGL9HYZRHBZ9FPJFWXRIGTXJSKMADGPODWYMCQYZ9999` - IOTA address
+ data_type: `WT` - 產能設備
+ date: `2020/02/14` - 日期
+ id: `049a9c28-c0cc-418e-9f35-23f6bc43df7e` - PowerData UUID
+ power_display: `2.471` (number) - 電力資訊
+ time: `23:51` - 時間

### ChartData1
+ Demand: `-7.486` (number)- 淨負載
+ ESS: `-3.211` (number) - ESS
+ EV: `-3.592` (number) - EV
+ PV: `-4.121` (number) - PV
+ WT: `-2.267` (number) - WT
+ name: `2020/02/14 00:00` (string) - 資料時間

### ChartData2
+ Demand: `-1.171` (number)- 淨負載
+ ESS: `2.076` (number) - ESS 資訊
+ EV: `-3.277` (number) - EV
+ PV: `0.055` (number) - PV
+ WT: `-2.146` (number) - WT
+ name: `2020/01/14 01:00` (string) - 資料時間

### HomepageBid1
+ date: `2020/04/23` - 日期
+ time: `23:00-00:00` - 時段
+ price: `4.5` (number) - 單價
+ volume: `30` (number) - 得標度數

### HomepageBid2
+ date: `2020/04/23` - 日期
+ time: `13:00-14:00` - 時段
+ price: `4.0` (number) - 單價
+ volume: `35` (number) - 得標度數