version: '3'
services:
  postgres:
    # checking connection: $ docker exec -it  ET_DB_POSTGRE psql -U {POSTGRES_USER} -W {POSTGRES_DB}
    image: postgres:11-alpine
    container_name: ET_DB_POSTGRE
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/dev-data
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ACCOUNT}
      POSTGRES_PASSWORD: ${DB_PASSWD}
  et-platform:
    image: et_platform:latest
    container_name: ET_PLATFORM
    restart: always
    env_file: ./production/.env
    ports:
      - 5000:5000
