version: '3'
services:
  postgres:
    # checking connection: $ docker exec -it  ET_DB_POSTGRE psql -U {POSTGRES_USER} -W {POSTGRES_DB}
    image: postgres:11-alpine
    container_name: ET_DB_POSTGRE
    restart: always
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
      # mounting create uuid extension statement to initialization folder in container.
      - ./db_script/create_uuid_extension.sql:/docker-entrypoint-initdb.d/create_uuid_extension.sql
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ACCOUNT}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    env_file: ./.env
  et-platform:
    image: et_platform:latest
    container_name: ET_PLATFORM
    restart: always
    env_file: ./production/.env
    volumes:
      - ${SSL_PATH}/fullchain.pem:/pt/certificate/fullchain.pem
      - ${SSL_PATH}/privkey.pem:/pt/certificate/privkey.pem
    ports:
      - 5000:5000
