"""user ethereum secret

Revision ID: 1e2c4d02cd4f
Revises: 3103135bfb76
Create Date: 2020-11-30 00:30:06.558234

"""
from alembic import op
import sqlalchemy as sa


# required if base_model or ModelMixin is used,
# so that utils.base_model's class can be referenced.
import sys
sys.path.insert(0, "./pt")
import utils

# revision identifiers, used by Alembic.
revision = '1e2c4d02cd4f'
down_revision = '3103135bfb76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'DR_bid', ['uuid'])
    op.add_column('user', sa.Column('contract_creator', sa.Boolean(), nullable=True, default=False))
    op.add_column('user', sa.Column('eth_secret', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'eth_secret')
    op.drop_column('user', 'contract_creator')
    op.drop_constraint(None, 'DR_bid', type_='unique')
    # ### end Alembic commands ###
