"""empty message

Revision ID: 3103135bfb76
Revises: ddc2ed927aca
Create Date: 2020-11-23 10:37:21.882099

"""
from alembic import op
import sqlalchemy as sa


# required if base_model or ModelMixin is used,
# so that utils.base_model's class can be referenced.
import sys
sys.path.insert(0, "./pt")
import utils

# revision identifiers, used by Alembic.
revision = '3103135bfb76'
down_revision = 'ddc2ed927aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DR_bid',
    sa.Column('uuid', utils.base_models.UUID2STR(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('executor', sa.String(), nullable=False),
    sa.Column('acceptor', sa.String(), nullable=True),
    sa.Column('start_time', utils.base_models.UTCDatetime(), nullable=False),
    sa.Column('end_time', utils.base_models.UTCDatetime(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('settlement', sa.Float(), nullable=True),
    sa.Column('blockchain_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'bidsubmit', ['uuid'])
    op.create_unique_constraint(None, 'history', ['uuid'])
    op.create_unique_constraint(None, 'matchresult', ['uuid'])
    op.create_unique_constraint(None, 'news', ['uuid'])
    op.create_unique_constraint(None, 'powerdata', ['uuid'])
    op.create_unique_constraint(None, 'tenders', ['uuid'])
    op.create_unique_constraint(None, 'user', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'tenders', type_='unique')
    op.drop_constraint(None, 'powerdata', type_='unique')
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_constraint(None, 'matchresult', type_='unique')
    op.drop_constraint(None, 'history', type_='unique')
    op.drop_constraint(None, 'bidsubmit', type_='unique')
    op.drop_table('DR_bid')
    # ### end Alembic commands ###
