"""add trading_mode and order_method

Revision ID: 6b007366be97
Revises: cc6358620fe0
Create Date: 2021-03-06 14:51:34.525900

"""
from alembic import op
import sqlalchemy as sa


# required if base_model or ModelMixin is used,
# so that utils.base_model's class can be referenced.
import sys
sys.path.insert(0, "./pt")
import utils

# revision identifiers, used by Alembic.
revision = '6b007366be97'
down_revision = 'cc6358620fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DR_bid', sa.Column('trading_mode', sa.Integer(), nullable=True))
    op.add_column('DR_bid', sa.Column('order_method', sa.String(), nullable=True))
    op.execute('''UPDATE public."DR_bid" SET trading_mode=1;''')
    op.execute('''UPDATE public."DR_bid" SET order_method='日前';''')
    op.alter_column('DR_bid', 'trading_mode', nullable=False)
    op.alter_column('DR_bid', 'order_method', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DR_bid', 'trading_mode')
    op.drop_column('DR_bid', 'order_method')
    # ### end Alembic commands ###
