"""add real_volume

Revision ID: bf2d463c333d
Revises: 6b007366be97
Create Date: 2021-04-09 14:37:33.034154

"""
from alembic import op
import sqlalchemy as sa


# required if base_model or ModelMixin is used,
# so that utils.base_model's class can be referenced.
import sys
sys.path.insert(0, "./pt")
import utils

# revision identifiers, used by Alembic.
revision = 'bf2d463c333d'
down_revision = '6b007366be97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DR_bid', sa.Column('real_volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DR_bid', 'real_volume')
    # ### end Alembic commands ###
