"""rename volume to bid_volume,
   add win_volume, demand_volume and cbl

Revision ID: ec3138328c31
Revises: 6b007366be97
Create Date: 2021-04-06 21:38:02.437064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# required if base_model or ModelMixin is used,
# so that utils.base_model's class can be referenced.
import sys
sys.path.insert(0, "./pt")
import utils

# revision identifiers, used by Alembic.
revision = 'ec3138328c31'
down_revision = '6b007366be97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DR_bid', sa.Column('bid_volume', sa.Float(), nullable=False))
    op.add_column('DR_bid', sa.Column('cbl', sa.Float(), nullable=True))
    op.add_column('DR_bid', sa.Column('win_volume', sa.Float(), nullable=True))
    op.add_column('DR_bid', sa.Column('demand_volume', sa.Float(), nullable=True))
    op.drop_column('DR_bid', 'volume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DR_bid', sa.Column('volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('DR_bid', 'win_volume')
    op.drop_column('DR_bid', 'cbl')
    op.drop_column('DR_bid', 'bid_volume')
    op.drop_column('DR_bid', 'demand_volume')
    # ### end Alembic commands ###
